### ISSUE TITLE
Parameterized Image Name by Environment

### ISSUE THREAD

**Issue by TheConnMan** [tongueroo/ufo#10]
Is it possible to parameterize the image name in `settings.yml` so it can be changed by environment? my use case is deploying the same app to multiple environments hosted in different AWS accounts, so the ECR image name is different for each environment.

**Comment by tongueroo** [comment]
@TheConnMan Good point. Going to think about how to handle this.

**Comment by TheConnMan** [comment]
Sweet, thank you. It might fall under the general idea of using different AWS accounts per environment. Not sure if that means being able to have entirely different configs in environment subsections instead of allowing per-environment toggles for only the Docker image.

**Comment by tongueroo** [comment]
Completely makes sense. Different AWS accounts is a great use case.

**Comment by tongueroo** [comment]
Still a work in progress. Here's a preview: https://github.com/tongueroo/ufo/blob/version-3/lib/ufo/default/settings.yml   The new format will really clean up aws_profile to ufo_env mapping from the users perspective also.

**Comment by tongueroo** [comment]
Put together a [ufo upgrade3](https://github.com/tongueroo/ufo/blob/version-3/lib/ufo/upgrade3.rb) command the next version that will update `settings.yml` to the new format 👍

**Comment by tongueroo** [comment]
@TheConnMan This pull request takes care of this https://github.com/tongueroo/ufo/pull/16. To upgrade run `ufo upgrade3.  The newer version also has auto-completion now http://ufoships.com/docs/auto-completion/ 🎉

**Comment by TheConnMan** [comment]
Thank you @tongueroo for the quick turnaround!
