### ISSUE TITLE
upgrade to V5

### ISSUE THREAD

**Issue by toneplex** [tongueroo/ufo#107]
I don't see any upgrade instructions for version 4.5 to 5.0.  Just wanted to check if there is anything I should do for the upgrade?

**Comment by tongueroo** [comment]
v5 is backwards compatible with v4. Should probably add a note about that in the upgrade though. Will consider PRs. No sweat either way. Thanks!

**Comment by toneplex** [comment]
Great, thanks.

**Comment by tongueroo** [comment]
Added v5 upgrade docs https://ufoships.com/docs/upgrading/upgrade5/
