### ISSUE TITLE
Production - Staging Environments

### ISSUE THREAD

**Issue by moisesrodriguez** [tongueroo/ufo#12]
Hi, I'm new to ECS and I have an app running on it right now. I used this tutorial to get it working https://www.ybrikman.com/writing/2015/11/11/running-docker-aws-ground-up/. It works but every deployment is a very manual process. So I ran into this tool. It looks like exactly what I was looking for. My idea is to have CircleCi run ufo so my deployments are not manual anymore. Currently I only have CircleCi create and deploy the docker image to ECS. In looking at ufoships.com/docs, I have a question in how can I create a production and staging environment? Do they go in the same cluster? How does ufo handle them? Any help would be much appreciated.

Thanks!

**Comment by tongueroo** [comment]
@moisesrodriguez Sorry for the late response. Going to see if I can figure out how to fix my inbox noise.

RE: how can I create a production and staging environment? 
Run: 

```ufo ship demo-web --cluster mycluster ```

You can also set up a AWS_PROFILE to cluster mapping so you dont always have to type it over and over.  Covered here: http://ufoships.com/docs/settings/
Internally the ship command will create the ECS cluster. You'll still need to make sure that you have container instances registered to the ECS cluster name.  

RE: Do they go in the same cluster? 
The ECS services can be deployed to different clusters with the `--cluster` option.

RE: How does ufo handle them? Any help would be much appreciated.
Hope the answers above covered it. 👍
