### ISSUE TITLE
Bolts - ufo version

### ISSUE THREAD

**Issue by moisesrodriguez** [tongueroo/ufo#19]
I'm using a mac and installed `ufo` via homebrew `brew cask install boltopslabs/software/bolts`. However I noticed that the ufo version it comes with is 2.0.0 and the latest release is 3.0.1. Been trying to find out how to update my `ufo` but can't find how. Any pointers would be much appreciated.

**Comment by tongueroo** [comment]
@moisesrodriguez  Sorry about that. the brew cask is out of date right now. Recommend install with rubygems for now until the package is updated.

```
gem install ufo
```

Hope that helps!

**Comment by moisesrodriguez** [comment]
Will do that, thanks!

**Comment by tongueroo** [comment]
@moisesrodriguez FWIW, updated the bolts installer package.

**Comment by tongueroo** [comment]
https://www.boltops.com/toolbelt

**Comment by moisesrodriguez** [comment]
@tongueroo Thanks!
