### ISSUE TITLE
Ufo vs ecs-deploy?

### ISSUE THREAD

**Issue by pikeas** [tongueroo/ufo#22]
I'm currently using https://github.com/silinternational/ecs-deploy and recently discovered ufo.

Could you compare and contrast `ufo ship` and `ecs-deploy`? It's great that ufo has increased scope (`build`, `task`, more control over definitions, etc), but I'm curious how the core deployment workflow differs?

**Comment by tongueroo** [comment]
@pikeas Sure. Just read over ecs-deploy. Some differences:

* ecs-deploy is implemented in bash
* ufo is implemented in ruby
* ecs-deploy is a simpler, which could work better for you. It’s nice that it’s one bash script. 

ufo does 3 things:

1. Builds and pushes the Docker image
2. Builds and registers the task definition with ECS
3. Deploys by either creating or updating the ECS service 

I believe ecs-deploy does step 2 and 3 but not step 1. For step 3, doesn’t look like ecs-deploy creates a service if it doesn’t exist. It’s more designed to update existing an ECS service.  

The main difference is that ecs-deploy downloads current ECS task definition and replaces the image attribute. ufo regenerates the task definition from code each deploy. If you’re making adjustments to the task definition with the ECS console as your flow, the ecs-deploy makes more sense. If you want to keep your task definition codified than ufo makes more sense.

Some more differences:

* ufo creates the CloudWatch log group if doesn’t exist. Small thing but it’s easy to forget. 
* ufo has a concept of variables that get layered. This is how it handles multi environments with very similar task definitions with just a few differences. 

Generally, ufo does more in scope so we’re sort of comparing apples to oranges here.  Hope that helps.
