### ISSUE TITLE
Passing additional options to task command

### ISSUE THREAD

**Issue by lostinpatterns** [tongueroo/ufo#29]
My task definition uses FARGATE as a launch type, which I believe requires the awsvpc networking mode. That means in order to run my task, I need to be able to pass additional options to the run-task command, eg:  

`--network-configuration "awsvpcConfiguration={assignPublicIp=ENABLED,subnets=[subnet-aaa],securityGroups=[sg-bbb]}"`

Would you accept a pull request for this, and if so, would you want additional options to run-task simply appended to the ufo `run task` command like the cluster option is?

**Comment by lostinpatterns** [comment]
OK cool, yeah I couldn't use ufo to create the Fargate services either for the same reason. You can add these options to your task definition template to test:

`
"requiresCompatibilities": ["FARGATE"],
"networkMode": "awsvpc",
"executionRoleArn": "<%= @execution_role_arn %>",
`

I think I should have some time this weekend to play around with it.

**Comment by tongueroo** [comment]
@lostinpatterns Added fargate support with #31.  Ending up introducing a new conceptual file called `.ufo/params.yml`.  The file `.ufo/params.yml` allows you to adjust the parameters that get sent to the [aws-sdk run_task](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ECS/Client.html#run_task-instance_method) method.  This allows support for Fargate and any other thing that the aws-sdk might add in the future. More info here: [Ufo Params Docs](http://ufoships.com/docs/params/) 

Also provided a `ufo upgrade3_3_to_3_4` command that creates the starter `.ufo/params.yml`. Run and follow instructions if you're already on version 3.3:

    ufo upgrade3_3_to_3_4

It's pretty awesome to be able to run an one off task and only pay for that task with fargate.

Closing this out.

**Comment by lostinpatterns** [comment]
Sorry for the really slow turnaround - got pulled on to something else so had to step away from the project I was working on that was using ufo. I just upgraded ufo in that project, set up my params file, and ran a one-off task for it on Fargate. Worked great, thank you!
