### ISSUE TITLE
Variables are not available in params.yml

### ISSUE THREAD

**Issue by hnatt** [tongueroo/ufo#40]
I would like to have different subnets and security groups for production and staging clusters and am looking for the ways to do this. Subnets and security groups are set in `params.yml`, but this file does not seem to have a notion of environments.

The [docs on params.yml](http://ufoships.com/docs/params/) say:

> ERB and variables are available in the params file

But I have a different experience. `instance_variables` in the context of params.yml ERB is empty and `self` seems to be an instance of `Object` without any additional methods.

So how do I access variables from the params files?

**Comment by tongueroo** [comment]
@hnatt  Think the docs are inaccurate here. It would be really nice to have access to shared variables in params though. Will try again.

**Comment by tongueroo** [comment]
@hnatt Fixed in version 3.5.5 [CHANGELOG](https://github.com/tongueroo/ufo/blob/master/CHANGELOG.md). Thanks for the report.
