### ISSUE TITLE
Docker image fails to push

### ISSUE THREAD

**Issue by joeyvmason** [tongueroo/ufo#50]
I am trying to build and push the demo, but am getting this error:

```
Building docker image with:
  docker build -t tongueroo/demo-ufo:ufo-2018-10-19T16-35-07-eb0789a -f Dockerfile .
Sending build context to Docker daemon    105kB
Step 1/10 : FROM ruby:2.5.1
 ---> 3c8181e703d2
Step 2/10 : WORKDIR /app
 ---> Using cache
 ---> 6f32cccb1763
Step 3/10 : ADD Gemfile /app/Gemfile
 ---> Using cache
 ---> 834f52b91aa7
Step 4/10 : ADD Gemfile.lock /app/Gemfile.lock
 ---> Using cache
 ---> 47da938fec85
Step 5/10 : RUN bundle install --system
 ---> Using cache
 ---> 85b22cc531ff
Step 6/10 : ADD . /app
 ---> Using cache
 ---> e3e5473cafda
Step 7/10 : RUN bundle install --system
 ---> Using cache
 ---> 876dd45bc20b
Step 8/10 : EXPOSE 4567
 ---> Using cache
 ---> e9f4e3a77519
Step 9/10 : RUN chmod a+x bin/*
 ---> Using cache
 ---> ea6323a7c4e4
Step 10/10 : CMD ["bin/web"]
 ---> Using cache
 ---> 0ad5ec7460fe
Successfully built 0ad5ec7460fe
Successfully tagged tongueroo/demo-ufo:ufo-2018-10-19T16-35-07-eb0789a
Docker image tongueroo/demo-ufo:ufo-2018-10-19T16-35-07-eb0789a built.  
Docker build took 0s.
=> docker push tongueroo/demo-ufo:ufo-2018-10-19T16-35-07-eb0789a
The push refers to repository [docker.io/tongueroo/demo-ufo]
0eba6c28d7bc: Preparing 
4f8e6bd38f44: Preparing 
b4446fb7ed07: Preparing 
01c08c0fd4ad: Preparing 
6da5e8658278: Preparing 
0f8c9434318c: Waiting 
a4172301657f: Waiting 
3696bfafb5ed: Waiting 
dda5ada3fa53: Waiting 
f5e615773459: Waiting 
9978d084fd77: Waiting 
1191b3f5862a: Waiting 
08a01612ffca: Waiting 
8bb25f9cdc41: Waiting 
f715ed19c28b: Waiting 
denied: requested access to the resource is denied
ERROR: The docker image fail to push.
```

I'm admittedly pretty new to Docker, but I believe the issue is that this process does not have permission to push to the Docker repository. However, I'm not understanding how to configure the repository. Is this something that needs to be done within the UFO framework config? How do you configure what repository to push to?

**Comment by tongueroo** [comment]
@joeyvmason I see. You're getting a push error because it's my tongueroo dockerhub account. So only I can push to that. Sorry meant the commands to served as an example.  

What you probably want to do:

You'll need to create your own dockerhub account and then use `docker login` command to log into your account and be able to push to that.

Then use your own image name. So something like this:

    gem install ufo
    git clone https://github.com/tongueroo/demo-ufo.git demo
    cd demo
    ufo init --image=joeyvmason/demo-ufo
    ufo current --service demo-web
    ufo ship
    
Hope that helps. Closing the issue, but feel free to comment additionally.

**Comment by tongueroo** [comment]
Here's some additional help info from docker's site: https://docs.docker.com/docker-id/#register-for-a-docker-id

**Comment by joeyvmason** [comment]
Works perfectly, thank you!

**Comment by tongueroo** [comment]
@joeyvmason Happy it worked out. Also if you're new to Docker, your might find blog post helpful: [Docker Crash Course Introduction Tutorial: Common Commands
](https://blog.boltops.com/2018/04/19/docker-introduction-tutorial)
