### ISSUE TITLE
is it mandatory to have docket hub account to deploy?

### ISSUE THREAD

**Issue by tushariscoolster** [tongueroo/ufo#52]
is it mandatory to have docket hub account to deploy?

**Comment by tongueroo** [comment]
@tushariscoolster No. The doc examples use dockerhub but you can use ecr or whatever you have access to.

**Comment by et304383** [comment]
We're deploying to ECS, so it would be nice if the demo example assumed pushing to an ECR repository and not docker hub.  :(
