### ISSUE TITLE
Task definitions per environment

### ISSUE THREAD

**Issue by et304383** [tongueroo/ufo#53]
I don't like the idea of environments being handled through different versions of the same task definition name.

I'd rather have my-app-dev, my-app-prod, etc.

I see no way to customize the task definition name in ufo.  Am I missing something or is this a new feature to be added?

**Comment by tongueroo** [comment]
@et304383 You can customize the task definition name with `.ufo/task_definitions.rb`. Docs here: [Task Definitions](http://ufoships.com/docs/tutorial-ufo-tasks-build/)

You can add `-dev`, `-prod`, etc to the task definition definitions declarations. Example:

```ruby
task_definition "demo-web-prod" do
  source "main" # will use ufo/templates/main.json.erb
  variables(
    family: task_definition_name,
    name: "web",
    container_port: helper.dockerfile_port,
    command: ["bin/web"]
  )
end

task_definition "demo-web-dev" do
  source "main" # will use ufo/templates/main.json.erb
  variables(
    family: task_definition_name,
    name: "web",
    container_port: helper.dockerfile_port,
    command: ["bin/web"]
  )
end
````

It introduces some duplication. If you're cool with that then you're done. 

Also, you could do some things with the `UFO_ENV` to remove some duplication. Example:

```ruby
env_map = {
  development: 'dev',
  production: 'prod',
}
env = env_map[Ufo.env.to_sym] || Ufo.env
task_definition "demo-web-#{env}" do
  source "main" # will use ufo/templates/main.json.erb
  variables(
    family: task_definition_name,
    name: "web",
    container_port: helper.dockerfile_port,
    command: ["bin/web"]
  )
end
````

Though you might want to make sure to set UFO_ENV when you deploy. This is where a `bin/deploy` wrapper script would make sense.  Something like:

bin/deploy:

```sh
#!/bin/bash

if [ "$#" -lt 1 ]; then
  echo "Usage:"
  echo "  bin/deploy demo-web-dev"
  echo "  bin/deploy demo-web-prod"
fi

TASK=$1
SHORT_UFO_ENV=$(echo ${TASK} | awk -F"-" '{ print $3}') # grab 3rd word

# map short env to UFO_ENV
#   dev => development
#   prod => production
case SHORT_UFO_ENV in
dev*)
  UFO_ENV=development
  ;;
prod*)
  UFO_ENV=production
  ;;
*)
  UFO_ENV=development
  ;;
esac

export UFO_ENV
ufo deploy $TASK
```

Hope that helps. Closing this out.

**Comment by et304383** [comment]
Ugh.  That is very clunky and not very user friendly (imo).

I was hoping ufo could make working with ECS a little easier, but this type of file editing required just to have task definitions named after environments is trading one set of problems for another.

Take my opinion with a grain of salt, as I'm sure a lot of work has been put into ufo and I really wanted it to work, but the need to edit so many config files and now ruby code too means it's just beyond where we want to be with a tool to interact with ECS.

**Comment by tongueroo** [comment]
@et304383 Okay. Thanks for the feedback 👌
