### ISSUE TITLE
proxy task's exit code for one off tasks

### ISSUE THREAD

**Issue by everplays** [tongueroo/ufo#58]
I have integrated UFO into our continues deployment and so far, everything is working well. However, I can think of cases that the deployment needs to be stopped specially when dealing with migrations.

Currently, in the deployment script, I do something like `ufo task web-worker -c bundle exec rake db:migrate` before `ufo ships web-{web,worker}`. Even though it hasn't happened yet, I can think of scenarios where migration fails and I want to prevent the `ufo ships` command to happen. This can be implemented if `ufo task` returns the exit code of the execution on the server.

## What I have in mind:

Adding a flag to `ufo task` to make it wait for the execution to finish with a desired timeout:

```bash
ufo task web-worker -t 300 -p -c bundle exec rake db:migrate
# -t for timeout, and -p for proxy unless you have a better suggestion.
```

## Implementation:

It will be fairly simple:

- use `aws ecs wait tasks-stopped` with the provided timeout.
- use `aws ecs describe-tasks` to extract the exit code and exit with it.

I would like to implement this if you agree with the idea.

**Comment by tongueroo** [comment]
@everplays This sounds dandy. Didn't realized that we could use the output of `describe_tasks` to extract the exit code. Just played with it to see where the exit code is.  Here's an example output:

```json
{
    "tasks": [
        {
            "taskArn": "arn:aws:ecs:us-west-2:112233445566:task/f628530d-e7b9-480e-86e6-ed48fc4e7bc2",
            "clusterArn": "arn:aws:ecs:us-west-2:112233445566:cluster/development",
            "taskDefinitionArn": "arn:aws:ecs:us-west-2:112233445566:task-definition/demo-web:34",
            "overrides": {
                "containerOverrides": [
                    {
                        "name": "web",
                        "command": [
                            "uptime"
                        ]
                    }
                ]
            },
            "lastStatus": "STOPPED",
            "desiredStatus": "STOPPED",
            "cpu": "256",
            "memory": "512",
            "containers": [
                {
                    "containerArn": "arn:aws:ecs:us-west-2:112233445566:container/04375cd1-04ff-4d8b-8f19-d792db7ad8bf",
                    "taskArn": "arn:aws:ecs:us-west-2:112233445566:task/f628530d-e7b9-480e-86e6-ed48fc4e7bc2",
                    "name": "web",
                    "lastStatus": "STOPPED",
                    "exitCode": 0,
                    "networkBindings": [],
                    "networkInterfaces": [
                        {
                            "attachmentId": "206e8a3e-eeaa-4e36-8cce-f5db2bb6cd61",
                            "privateIpv4Address": "172.31.20.5"
                        }
                    ],
                    "healthStatus": "UNKNOWN"
                }
            ],
            "version": 5,
            "stoppedReason": "Essential container in task exited",
            "connectivity": "DISCONNECTED",
            "connectivityAt": 1543362774.083,
            "pullStartedAt": 1543362741.152,
            "pullStoppedAt": 1543362820.152,
            "executionStoppedAt": 1543362821.0,
            "createdAt": 1543362728.52,
            "startedAt": 1543362821.152,
            "stoppingAt": 1543362821.502,
            "stoppedAt": 1543362834.256,
            "group": "family:demo-web",
            "launchType": "FARGATE",
            "platformVersion": "1.2.0",
            "attachments": [
                {
                    "id": "206e8a3e-eeaa-4e36-8cce-f5db2bb6cd61",
                    "type": "ElasticNetworkInterface",
                    "status": "DELETED",
                    "details": [
                        {
                            "name": "subnetId",
                            "value": "subnet-5b08b922"
                        },
                        {
                            "name": "networkInterfaceId",
                            "value": "eni-d5ea9738"
                        },
                        {
                            "name": "macAddress",
                            "value": "02:15:22:4d:2a:80"
                        },
                        {
                            "name": "privateIPv4Address",
                            "value": "172.31.20.5"
                        }
                    ]
                }
            ],
            "healthStatus": "UNKNOWN"
        }
    ],
    "failures": []
}
```

Guessing ufo would like for `"stoppedReason": "Essential container in task exited"` and that would be a success. 

Would love to see this included. Happy to take a look at what you come up with.

Also, initial go though on options:

    ufo task web-worker --timeout 300 --wait --command bundle exec rake db:migrate
    ufo task web-worker --t 300 -w -c bundle exec rake db:migrate

Think `--wait` feels more natural. as it'll wait for the tasks to finish and then return the proper exit code.

**Comment by everplays** [comment]
@tongueroo `--wait` indeed is a better choice.

About extracting the status, actually I was thinking to use `exitCode` because it's more unix-y:

> "exitCode": 0,

^ is from the example that you have shared. This way, if the executed command exited with status 10, we also exit ufo with status 10.

**Comment by tongueroo** [comment]
@everplays Oh awesome. I'm blind as a bat. Didn't see `exitCode`. Thanks for sharing! 👍
