### ISSUE TITLE
Colorize and GPL

### ISSUE THREAD

**Issue by gssbzn** [tongueroo/ufo#62]
I find this tool interesting tool and we're evaluating using it but I couldn't but notice that it is using colorize, which is a GPL library, https://github.com/fazibear/colorize/blob/master/LICENSE
While  this project label itself as MIT using using colorize as a dependency also grants users a GPL license

**Comment by tongueroo** [comment]
@gssbzn Using the [sickill/rainbow](https://github.com/sickill/rainbow) gem now. Released in [4.2.0](https://github.com/tongueroo/ufo/blob/master/CHANGELOG.md).
