### ISSUE TITLE
Service placement strategy settings

### ISSUE THREAD

**Issue by MaartenDCrius** [tongueroo/ufo#65]
Hi,

Is it possible to add a placement_strategy during the deploy of a service?

Loving the tool!

Kind regards

**Comment by tongueroo** [comment]
Thanks for the kind words.  👍

Can possibly do this right now by customizing the CloudFormation template like `.ufo/settings/cfn/default.yml` and addig an `Ecs` entry to adjust the [AWS::ECS::Service](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html) resource. http://ufoships.com/docs/customize-cloudformation/  The properties get appended to the generated CloudFormation template and then will get used. This will set placement_strategy for all the tasks.

This is very similar to the `--scheduling-strategy` option that was addressed here:

* https://github.com/tongueroo/ufo/issues/54
* https://github.com/tongueroo/ufo/issues/55

Might dig into adding a `--placement-strategies` option. Unsure when. The way the `--scheduling-strategy` works is that it keeps its state so users don't have to remember to type the option again in the future. Only if they want to change it, then they explicitly use the option again.

Feels like placement strategy is something that would be used for all the tasks though, so the CloudFormation customization might suffice for what you currently need.  Think both options are good though.

Happy to also consider PRs here. No sweat either way 👌

**Comment by MaartenDCrius** [comment]
I added this in the default.yml and it worked 

```yaml
ecs:
  placement_strategies: 
    - type: spread
      field: instanceId
```

**Comment by tongueroo** [comment]
Think that the current solution to adjust the cfn/default.yml is okay for placement strategies so closing out.
