### ISSUE TITLE
Is NatGateway supported?

### ISSUE THREAD

**Issue by mehedisd** [tongueroo/ufo#72]
Is it possible to configure a nat gateway with UFO and launch ecs services in private subnets and route traffic through that nat gateway to public internet ?

**Comment by tongueroo** [comment]
Yes. This is supported. You can configure the ELB be on the public subnets and the ECS tasks on private subnets. This is configurable with [Network Settings](http://ufoships.com/docs/settings-network/)  Options are also documented in the CLI reference [ufo init](http://ufoships.com/reference/ufo-init/)
