### ISSUE TITLE
Secrets in Container Definitions

### ISSUE THREAD

**Issue by jayodeji** [tongueroo/ufo#76]
This is a similar question to this: #63, however with some differences.

1. I see that aws now has support for specifying a secrets object in the container definitions: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html

The questions I have are:

1. is it possible to create custom helpers that can actually take a secrets environment variable and inject it into the container definitions, similar to the `full_image_name` and `env_vars` helpers. So I would do something like the below in base.rb or another variables file:
```ruby
@secrets = helper.secrets(%Q[
    DB_PASSWORD=/my_app/db_password
    APP_KEY=/my_app/app_key
])
```
which would convert it to something like this:
```json
[{
    "name": "DB_PASSWORD",
    "valueFrom": "/my_app/db_password"
},
{
    "name": "APP_KEY",
    "valueFrom": "/my_app/app_key"
}]
```
Which i would then add to the container definitions in `main.json.erb` like below:

```ruby
<% if @secrets %>
      "secrets": <%= @secrets.to_json %>,
<% end %>
```

This would allow me to inject secrets into my containers using aws cloudformation's new way of injecting secrets.

2. Is it possible to interpolate environment variables into our variable declaration, for instance in the example above:
```ruby
@secrets = helper.secrets(%Q[
    DB_PASSWORD=/my_app/db_password
    APP_KEY=/my_app/app_key
])
```
changing that to be:
```ruby
@secrets = helper.secrets(%Q[
    DB_PASSWORD=/my_app-{environment}/db_password
    APP_KEY=/my_app-{environment}/app_key
])
```

**Comment by jayodeji** [comment]
As an addendum, looks like their is no support in cloudformation yet for the Secrets object, but my earlier question still stands, about creating custom helpers, that I can possibly use to inject secrets into parameters.

**Comment by tongueroo** [comment]
Currently not possible but would like to see this added 👍 Somewhat relevant: https://github.com/tongueroo/jets/pull/233

Would probably create a module and include it into this [dsl/helper.rb](https://github.com/tongueroo/ufo/blob/master/lib/ufo/dsl/helper.rb). Will consider this PR!  Otherwise, will take a look at this in time.

**Comment by aaronlippold** [comment]
I also have one of my folks looking into adding the helper.secrets for SSM parameter and Secrets Manager. It seems to me we should have two PRs on this. One for SSM and one for secrets manager.

**Comment by tongueroo** [comment]
Sounds good

**Comment by alexbeattie42** [comment]
I came across this ticket and was hoping to use the SSM in fargate feature on a project I am working on at work. I am intrested in developing this for ufo and submitting a PR if that is desired.

**Comment by tongueroo** [comment]
Sure. Will consider it. Go for it.

**Comment by aaronlippold** [comment]
Yes. We would be happy to help as well

**Comment by tongueroo** [comment]
Handled by #106 Docs: https://ufoships.com/docs/secrets/
