### ISSUE TITLE
v4.4 release confused our deploy?

### ISSUE THREAD

**Issue by mepatterson** [tongueroo/ufo#77]
I'm still a bit confused by what happened exactly, but it seems related to the 4.4 upgrade. Hopefully you can provide some illumination...

Specifically, we have our CI system build and deploy our containers with UFO. This has been working flawlessly up until this morning. On our CI, we always just run `gem install ufo` (that's our bad for not version-locking it) before we run the ufo commands. It picked up 4.4 this morning, threw a bunch of warnings about the upgrade switching around how it names the stack, and then everything went nuts...

We're using custom cluster names:

```
staging:
  cluster: fancyapp-ufo-stag

production:
  cluster: fancyapp-ufo-prod
```

We did this to make it easier to read our stack and other resource names and disambiguate since we have multiple apps with different names. So we have stacks like `fancyapp-ufo-stag-fancyapp-web` and `fancyapp-ufo-prod-fancyapp-web`

We were deploying both our prod and stag servers, and all sorts of timeout errors occurred on ECS/Fargate, and then _some_ stacks seemed to deploy and were updated, but were running the WRONG ENVIRONMENTS (e.g. our 'prod' stack was running 'RAILS_ENV staging` somehow)? I'm super-confused how, exactly, it ended up like this. 

**Adjusting our CI to always do `gem install ufo -v '~> 4.3.0'` fixed everything and it deployed as normal.**

What exactly happened? And if we're using custom cluster names like above, how should we upgrade properly to 4.4 to avoid any issues?

**Comment by tongueroo** [comment]
@mepatterson 

> RE: And if we're using custom cluster names like above, how should we upgrade properly to 4.4 to avoid any issues?

Interesting. The version 4.4 upgrade path is here http://ufoships.com/docs/upgrading/upgrade4.4/ But thinking it won't work with the explicit cluster setting. 

The upgrade is supposed to create a new stack. Tested it but without an explicit cluster setting though. Thinking the explicit cluster setting messed up the deploy. To know more, the CloudFormation rollback error messages may be helpful. 

Off the top of my head, you may have to:

1. Comment out the cluster setting
2. Deploy and it'll create a stack name `fancyapp-ufo-production` - default if your app is named `fancyapp-ufo`
3. Point your DNS to that temporary cluster
4. Make sure there's no more traffic hitting the old ELB. One way is to check the ELB monitoring tab.
5. Delete the old cluster manually, via the CloudFormation console
6. Add back in the cluster setting
7. Deploy again
8. Point your DNS to that new cluster
9. Make sure there's no more traffic hitting the temporary ELB and cluster
10. Delete the temporary cluster

Hope that helps for now.
