### ISSUE TITLE
Health Check Grace Period

### ISSUE THREAD

**Issue by jdguzman** [tongueroo/ufo#83]
I had a look around and could not find any references to this setting for a service in a cluster. Is it possible to set this with UFO?

**Comment by tongueroo** [comment]
Should be able to, since the generated CloudFormation template properties can be configured: https://ufoships.com/docs/settings/cfn/

So add to `.ufo/settings/cfn/default.yml` something like this:

```yaml
ecs:
  health_check_grace_period_seconds: 60
```
